import { siteConfig } from "@/lib/site-config"

export const bannerSlides = [
  {
    id: 1,
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1200&h=600&fit=crop&crop=center",
  },
  {
    id: 2,
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=1200&h=600&fit=crop&crop=center",
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=1200&h=600&fit=crop&crop=center",
  },
  {
    id: 4,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=600&fit=crop&crop=center",
  },
]

export const studentSuccesses = [
  {
    id: 1,
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=300&fit=crop&crop=center",
    name: "นักเรียน A",
    achievement: "คะแนนฟิสิกส์ 95/100",
  },
  {
    id: 2,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center",
    name: "นักเรียน B", 
    achievement: "เข้ามหาวิทยาลัยชั้นนำ",
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=300&fit=crop&crop=center",
    name: "นักเรียน C",
    achievement: "ได้ทุนการศึกษา",
  },
  {
    id: 4,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop&crop=center",
    name: "นักเรียน D",
    achievement: "คะแนนฟิสิกส์เต็ม 100",
  },
  {
    id: 5,
    image: "https://images.unsplash.com/photo-1544717297-fa95b6ee9643?w=400&h=300&fit=crop&crop=center",
    name: "นักเรียน E",
    achievement: "ติดคณะวิศวกรรม",
  },
  {
    id: 6,
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=300&fit=crop&crop=center",
    name: "นักเรียน F",
    achievement: "ชนะเลิศการแข่งขัน",
  },
  {
    id: 7,
    image: "https://images.unsplash.com/photo-1580894894513-541e068a3e2b?w=400&h=300&fit=crop&crop=center",
    name: "นักเรียน G",
    achievement: "เข้าโครงการพิเศษ",
  },
  {
    id: 8,
    image: "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=400&h=300&fit=crop&crop=center",
    name: "นักเรียน H",
    achievement: "คะแนนสูงสุดในโรงเรียน",
  },
  {
    id: 9,
    image: "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=400&h=300&fit=crop&crop=center",
    name: "นักเรียน I",
    achievement: "ได้รับรางวัลเกียรตินิยม",
  },
]

export const reviews = [
  {
    id: 1,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop&crop=center",
    name: "สมชาย ใจดี",
    rating: 5,
    comment: "อาจารย์สอนดีมาก เข้าใจง่าย ได้คะแนนสอบเข้าสูงมาก",
  },
  {
    id: 2,
    image: "https://images.unsplash.com/photo-1544717297-fa95b6ee9643?w=400&h=300&fit=crop&crop=center",
    name: "สมหญิง รักเรียน",
    rating: 5,
    comment: "คอร์สเรียนครบถ้วน มีเทคนิคดีๆ เยอะมาก แนะนำเลย",
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=300&fit=crop&crop=center",
    name: "วิชัย เก่งฟิสิกส์",
    rating: 5,
    comment: "จากที่เคยไม่เข้าใจฟิสิกส์เลย ตอนนี้ชอบฟิสิกส์มากแล้ว",
  },
  {
    id: 4,
    image: "https://images.unsplash.com/photo-1580894894513-541e068a3e2b?w=400&h=300&fit=crop&crop=center",
    name: "สุดา ขยันเรียน",
    rating: 5,
    comment: "อาจารย์ใจดี ตอบคำถามละเอียด ช่วยเหลือดีมาก",
  },
  {
    id: 5,
    image: "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=400&h=300&fit=crop&crop=center",
    name: "ธนา มุ่งมั่น",
    rating: 5,
    comment: "เนื้อหาครบ อธิบายชัดเจน ทำให้เข้าใจฟิสิกส์มากขึ้น",
  },
  {
    id: 6,
    image: "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=400&h=300&fit=crop&crop=center",
    name: "นิดา ตั้งใจเรียน",
    rating: 5,
    comment: "คุ้มค่ามาก ได้ความรู้เยอะ คะแนนดีขึ้นเห็นได้ชัด",
  },
  {
    id: 7,
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=300&fit=crop&crop=center",
    name: "ปิยะ รักการเรียน",
    rating: 5,
    comment: "วิธีสอนเข้าใจง่าย มีตัวอย่างเยอะ ทำให้จำได้ดี",
  },
  {
    id: 8,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center",
    name: "มานะ พยายาม",
    rating: 5,
    comment: "เทคนิคการแก้โจทย์ดีมาก ช่วยให้ทำข้อสอบได้เร็วขึ้น",
  },
  {
    id: 9,
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=300&fit=crop&crop=center",
    name: "สิริ เรียนเก่ง",
    rating: 5,
    comment: "แนะนำให้เพื่อนๆ มาเรียนด้วย เพราะดีจริงๆ",
  },
]

export const books = [
  {
    id: 1,
    title: "คู่มือฟิสิกส์ระดับมัธยมปลาย",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop&crop=center",
    originalPrice: 990,
    discountPrice: 590,
    description: "หนังสือเรียนฟิสิกส์ครบถ้วน เหมาะสำหรับนักเรียนมัธยมปลาย พร้อมแบบฝึกหัดและเฉลย",
  },
  {
    id: 2,
    title: "สรุปสูตรฟิสิกส์ฉบับสมบูรณ์",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop&crop=center",
    originalPrice: 200,
    discountPrice: 0,
    description: "รวมสูตรฟิสิกส์ทั้งหมดในระดับมัธยมปลาย จัดหมวดหมู่ชัดเจน ใช้งานง่าย",
  },
  {
    id: 3,
    title: "เทคนิคการแก้โจทย์ฟิสิกส์",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop&crop=center",
    originalPrice: 690,
    discountPrice: 500,
    description: "เทคนิคและวิธีการแก้โจทย์ฟิสิกส์แบบเป็นระบบ พร้อมตัวอย่างข้อสอบ",
  },
  {
    id: 4,
    title: "ฟิสิกส์เพื่อการสอบเข้ามหาวิทยาลัย",
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop&crop=center",
    originalPrice: 200,
    discountPrice: 0,
    description: "เตรียมความพร้อมสำหรับการสอบเข้ามหาวิทยาลัย ครอบคลุมเนื้อหาทุกบท",
  },
]

export const articles = [
  {
    id: 1,
    slug: "physics-problem-solving",
    title: "เทคนิคการแก้โจทย์ฟิสิกส์ให้ได้คะแนนเต็ม",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=400&fit=crop&crop=center",
    excerpt: "การแก้โจทย์ฟิสิกส์ให้ได้คะแนนเต็มต้องมีเทคนิคและวิธีการที่ถูกต้อง มาดูกันว่ามีวิธีไหนบ้างที่จะช่วยให้คุณทำคะแนนได้ดีขึ้น",
    date: "2024-01-15",
  },
  {
    id: 2,
    slug: "physics-formulas-memorization",
    title: "วิธีจำสูตรฟิสิกส์ให้ไม่ลืม",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&h=400&fit=crop&crop=center",
    excerpt: "สูตรฟิสิกส์มีเยอะมาก แต่ถ้าเรารู้เทคนิคการจำที่ถูกต้อง จะทำให้เราจำได้นานและนำไปใช้ได้อย่างมีประสิทธิภาพ",
    date: "2024-01-10",
  },
  {
    id: 3,
    slug: "physics-fundamentals",
    title: "พื้นฐานฟิสิกส์ที่ต้องรู้ก่อนเรียนต่อ",
    image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&h=400&fit=crop&crop=center",
    excerpt: "ก่อนที่จะเรียนฟิสิกส์ในระดับสูงขึ้น สิ่งสำคัญคือต้องมีพื้นฐานที่แข็งแกร่ง มาดูกันว่าพื้นฐานอะไรบ้างที่จำเป็นต้องรู��",
    date: "2024-01-05",
  },
]
export const teachingVideos = [
  {
    id: 1,
    title: "การเคลื่อนที่แบบตรง",
    youtubeId: "09W1t7nVOm4", 
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=350&h=200&fit=crop&crop=center",
    description: "เรียนรู้เรื่องการเคลื่อนที่แบบตรงอย่างละเอียด พร้อมตัวอย่างและแบบฝึกหัด",
  },
  {
    id: 2,
    title: "แรงและการเคลื่อนที่",
    youtubeId: "GjZZf6UtVjc", 
    thumbnail: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=350&h=200&fit=crop&crop=center",
    description: "ทำความเข้าใจเรื่องแรงและการเคลื่อนที่ตามกฎของนิวตัน",
  },
  {
    id: 3,
    title: "พลังงานและงาน",
    youtubeId: "dQw4w9WgXcQ", 
    thumbnail: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=350&h=200&fit=crop&crop=center",
    description: "ศึกษาเรื่องพลังงานและงาน หลักการอนุรักษ์พลังงาน",
  },
  {
    id: 4,
    title: "คลื่นและเสียง",
    youtubeId: "dQw4w9WgXcQ", 
    thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=350&h=200&fit=crop&crop=center",
    description: "เรียนรู้เรื่องคลื่นกลและเสียง คุณสมบัติและการประยุกต์ใช้",
  },
]

export const socialLinks = [
  { platform: "TikTok", username: "@demo_physics", url: "https://tiktok.com/@demo_physics" },
  { platform: "Instagram", username: "@demo.physics", url: "https://instagram.com/demo.physics" },
  { platform: "Facebook", username: "@demophysics", url: "https://facebook.com/demophysics" },
  { platform: "Line", username: "@demo123", url: "https://line.me/ti/p/@demo123" },
]

export const contactInfo = {
  email: "contact@demo-physics.com",
  schoolName: siteConfig.fullName,
  subtitle: "(แพลตฟอร์มการเรียนรู้สำหรับทุกคน)",
  address: "สำนักงานใหญ่ : กรุงเทพมหานคร ประเทศไทย",
  hours: {
    vacation: "เปิดให้บริการ 24/7 ออนไลน์",
    semester: "เปิดให้บริการ 24/7 ออนไลน์",
  },
}

export const courseCategories = [
  { id: "all", name: "คอร์สทั้งหมด" },
  { id: "middle", name: "คอร์สม.ต้น" },
  { id: "high", name: "คอร์สม.ปลาย" },
  { id: "entrance", name: "คอร์สสอบเข้ามหาวิทยาลัย" },
  { id: "practice", name: "คอร์สตะลุยโจทย์" },
  { id: "other", name: "คอร์สวิชาอื่น ๆ" },
]

export const courses = [
  {
    id: 1,
    title: "ฟิสิกส์ม.6 เทอม 1 (อัพเดทแล้ว)",
    description: "คอร์สเนื้อหาม.6 เทอม 1 (หลักสูตรเข้มข้น)",
    image: "/physics-m6-term1-course-cover.png",
    category: "high",
    students: 65,
    lectures: 36,
    originalPrice: 4500,
    discountPrice: 3500,
    rating: 4.8,
    reviews: 12,
    instructor: "อาจารย์เต้ย",
    level: "ม.6",
    duration: "3 เดือน",
    whatYouWillLearn: [
      "การเคลื่อนที่แบบโปรเจกไทล์",
      "การเคลื่อนที่แบบวงกลม",
      "แรงและกฎการเคลื่อนที่ของนิวตัน",
      "งานและพลังงาน",
      "โมเมนตัมและการชน",
    ],
    prerequisites: ["ผ่านฟิสิกส์ ม.4-5 หรือมีพื้นฐานเทียบเท่า", "เข้าใจคณิตศาสตร์พื้นฐาน", "มีความตั้งใจเรียนรู้"],
    courseOverview: "คอร์สนี้จะสอนเนื้อหาฟิสิกส์ ม.6 เทอม 1 อย่างเข้มข้น เน้นการทำความเข้าใจหลักการและการประยุกต์ใช้ในการแก้โจทย์",
    videoSample: "dQw4w9WgXcQ",
  },
  {
    id: 2,
    title: "ENTRANCE PHYSICS #DEK69",
    description:
      "🟡 คอร์ส ENTRANCE PHYSICS #DEK69 🟡 สรุปเนื้อหาฟิสิกส์ม.ปลายทั้งหมด ไม่มีพื้นฐานก็เรียนได้ (สอนเนื้อหา+ลุยข้อสอบแยกบท รวม 7 เล่ม)",
    image: "/entrance-physics-dek69-course-cover.png",
    category: "entrance",
    students: 515,
    lectures: 154,
    originalPrice: 16500,
    discountPrice: 8900,
    rating: 4.9,
    reviews: 89,
    instructor: "อาจารย์เต้ย",
    level: "ม.ปลาย",
    duration: "6 เดือน",
    whatYouWillLearn: [
      "เนื้อหาฟิสิกส์ม.ปลายทั้งหมด",
      "เทคนิคการแก้โจทย์สอบเข้า",
      "การวิเคราะห์ข้อสอบแต่ละมหาวิทยาลัย",
      "การจัดการเวลาในการสอบ",
      "เทคนิคการจำสูตรอย่างมีประสิทธิภาพ",
    ],
    prerequisites: ["ไม่จำเป็นต้องมีพื้นฐาน", "ความตั้งใจเรียนรู้", "เวลาในการฝึกฝนอย่างสม่ำเสมอ"],
    courseOverview: "คอร์สเตรียมสอบเข้ามหาวิทยาลัยที่ครอบคลุมทุกเนื้อหา เหมาะสำหรับผู้ที่ต้องการคะแนนสูงในการสอบเข้า",
    videoSample: "dQw4w9WgXcQ",
  },
  {
    id: 3,
    title: "ฟิสิกส์ ม.5 เทอม 1 (อัพเดตแล้ว)",
    description: "คอร์สเนื้อหาม.5 เทอม 1 (หลักสูตรเข้มข้น)",
    image: "/physics-m5-term1-course-cover.png",
    category: "high",
    students: 72,
    lectures: 30,
    originalPrice: 4500,
    discountPrice: 3500,
    rating: 4.7,
    reviews: 15,
    instructor: "อาจารย์เต้ย",
    level: "ม.5",
    duration: "3 เดือน",
    whatYouWillLearn: ["คลื่นกล", "เสียง", "แสงและการมองเห็น", "ไฟฟ้าสถิต", "ไฟฟ้ากระแสตรง"],
    prerequisites: ["ผ่านฟิสิกส์ ม.4 หรือมีพื้นฐานเทียบเท่า", "เข้าใจคณิตศาสตร์พื้นฐาน"],
    courseOverview: "เรียนรู้ฟิสิกส์ ม.5 เทอม 1 อย่างเป็นระบบ เน้นความเข้าใจและการประยุกต์ใช้",
    videoSample: "dQw4w9WgXcQ",
  },
  {
    id: 4,
    title: "คอร์ส ม.4 เทอม 2 (อัพเดตแล้ว)",
    description: "เนื้อหา งานและพลังงาน การเคลื่อนที่แบบวิถีโค้ง การเคลื่อนที่แบบวงกลม โมเมนตัม สมดุลกล",
    image: "/physics-m4-term2-course-cover.png",
    category: "middle",
    students: 118,
    lectures: 30,
    originalPrice: 4500,
    discountPrice: 4000,
    rating: 4.6,
    reviews: 22,
    instructor: "อาจารย์เต้ย",
    level: "ม.4",
    duration: "3 เดือน",
    whatYouWillLearn: ["งานและพลังงาน", "การเคลื่อนที่แบบวิถีโค้ง", "การเคลื่อนที่แบบวงกลม", "โมเมนตัมและการชน", "สมดุลกล"],
    prerequisites: ["ผ่านฟิสิกส์ ม.4 เทอม 1", "เข้าใจคณิตศาสตร์พื้นฐาน"],
    courseOverview: "ต่อยอดจากฟิสิกส์ ม.4 เทอม 1 เรียนรู้เรื่องพลังงานและการเคลื่อนที่ขั้นสูง",
    videoSample: "dQw4w9WgXcQ",
  },
  {
    id: 5,
    title: "คอร์สสอวนฟิสิกส์",
    description: "เนื้อหา+ข้อสอบ พร้อมสอบสอวน ค่าย 1และ คอร์สนี้สามารถนำไปประยุกต์ในการสอบสนามอื่นๆได้อีกด้วย",
    image: "/physics-olympiad-course-cover.png",
    category: "practice",
    students: 58,
    lectures: 76,
    originalPrice: 5600,
    discountPrice: 4800,
    rating: 4.9,
    reviews: 8,
    instructor: "อาจารย์เต้ย",
    level: "ขั้นสูง",
    duration: "4 เดือน",
    whatYouWillLearn: [
      "เนื้อหาฟิสิกส์ระดับโอลิมปิค",
      "เทคนิคการแก้โจทย์ขั้นสูง",
      "การวิเคราะห์ปัญหาเชิงฟิสิกส์",
      "การเตรียมตัวสอบสอวน",
      "การประยุกต์ใช้ในการแข่งขัน",
    ],
    prerequisites: ["มีพื้นฐานฟิสิกส์ม.ปลายที่แข็งแกร่ง", "เข้าใจคณิตศาสตร์ขั้นสูง", "มีความมุ่งมั่นสูง"],
    courseOverview: "คอร์สเตรียมความพร้อมสำหรับการแข่งขันฟิสิกส์ระดับชาติ เน้นการแก้โจทย์ขั้นสูง",
    videoSample: "dQw4w9WgXcQ",
  },
  {
    id: 6,
    title: "คอร์สพื้นฐานฟิสิกส์ (FUNDAMENTAL PHYSICS) PART 1",
    description: "สอนเนื้อหาสำหรับคนพื้นฐานน้อยหรือไม่มีพื้นฐานเลย เป็นการติดกระดุมเม็ดแรกของฟิสิกส์ พื้นน้อยเรียนได้",
    image: "/fundamental-physics-part1-course-cover.png",
    category: "middle",
    students: 144,
    lectures: 36,
    originalPrice: 5600,
    discountPrice: 5600,
    rating: 4.5,
    reviews: 28,
    instructor: "อาจารย์เต้ย",
    level: "เริ่มต้น",
    duration: "2 เดือน",
    whatYouWillLearn: [
      "หลักการพื้นฐานของฟิสิกส์",
      "การวัดและหน่วย",
      "การเคลื่อนที่เบื้องต้น",
      "แรงและการเคลื่อนที่",
      "การสร้างพื้นฐานที่แข็งแกร่ง",
    ],
    prerequisites: ["ไม่จำเป็นต้องมีพื้นฐาน", "ความตั้งใจเรียนรู้"],
    courseOverview: "คอร์สสำหรับผู้เริ่มต้นที่ต้องการสร้างพื้นฐานฟิสิกส์ที่แข็งแกร่ง",
    videoSample: "dQw4w9WgXcQ",
  },
  {
    id: 7,
    title: "คอร์สฟิสิกส์ A LEVEL68",
    description: "คอร์สสอบเข้ามหาลัยเป็นแนวสรุปเนื้อหาและพาลุยข้อสอบแบบกระชับ ตุลยข้อสอบแนวใหม่ที่จะออกในปีนี้",
    image: "/physics-a-level68-course-cover.png",
    category: "entrance",
    students: 199,
    lectures: 81,
    originalPrice: 5600,
    discountPrice: 5600,
    rating: 4.8,
    reviews: 35,
    instructor: "อาจารย์เต้ย",
    level: "ม.ปลาย",
    duration: "4 เดือน",
    whatYouWillLearn: [
      "สรุปเนื้อหาฟิสิกส์ครบถ้วน",
      "เทคนิคการแก้โจทย์สอบเข้า",
      "ข้อสอบแนวใหม่ล่าสุด",
      "การจัดการเวลาในการสอบ",
      "เคล็ดลับการได้คะแนนสูง",
    ],
    prerequisites: ["มีพื้นฐานฟิสิกส์ม.ปลาย", "ความตั้งใจเตรียมสอบ"],
    courseOverview: "คอร์สเตรียมสอบเข้ามหาวิทยาลัยแบบเข้มข้น เน้นการทบทวนและลุยข้อสอบ",
    videoSample: "dQw4w9WgXcQ",
  },
  {
    id: 8,
    title: "คอร์สชีวะ ม.4 เทอม 1",
    description: "เนื้อหาชีววิทยา ม.4 เทอม 1 ครบถ้วน",
    image: "/biology-m4-term1-course-cover.png",
    category: "other",
    students: 0,
    lectures: 23,
    originalPrice: 4500,
    discountPrice: 3500,
    rating: 0,
    reviews: 0,
    instructor: "อาจารย์ชีวะ",
    level: "ม.4",
    duration: "3 เดือน",
    whatYouWillLearn: ["เซลล์และการทำงาน", "การสืบพันธุ์ของเซลล์", "พันธุศาสตร์เบื้องต้น", "วิวัฒนาการ", "ระบบนิเวศ"],
    prerequisites: ["ไม่จำเป็นต้องมีพื้นฐาน", "ความสนใจในชีววิทยา"],
    courseOverview: "เรียนรู้ชีววิทยา ม.4 เทอม 1 อย่างเป็นระบบและเข้าใจง่าย",
    videoSample: "dQw4w9WgXcQ",
  },
]

export const examCategories = [
  { id: "all", name: "ข้อสอบทั้งหมด", color: "rgb(250 202 21)" },
  { id: "pat2", name: "ข้อสอบ PAT2", color: "rgb(254 190 1)" },
  { id: "alevel", name: "ข้อสอบ A LEVEL", color: "rgb(0 75 125)" },
  { id: "physics-olympiad", name: "ข้อสอบสอวน.ฟิสิกส์ คัดค่าย 1", color: "rgb(255 90 31)" },
  { id: "tpat3", name: "ข้อสอบความถนัดวิศวกรรม (TPAT3)", color: "rgb(155 28 28)" },
]

export const examBank = [
 
  {
    id: 1,
    title: "ข้อสอบ PAT2 วิชา ฟิสิกส์ ปี 2552",
    category: "pat2",
    year: 2552,
    subject: "ฟิสิกส์",
    examType: "PAT2",
    pdfUrl: "/exams/pat2-physics-2552.pdf",
    downloadUrl: "/downloads/pat2-physics-2552.pdf",
  },
  {
    id: 2,
    title: "ข้อสอบ PAT2 วิชา ฟิสิกส์ ปี 2553",
    category: "pat2",
    year: 2553,
    subject: "ฟิสิกส์",
    examType: "PAT2",
    pdfUrl: "/exams/pat2-physics-2553.pdf",
    downloadUrl: "/downloads/pat2-physics-2553.pdf",
  },
  {
    id: 3,
    title: "ข้อสอบ PAT2 วิชา ฟิสิกส์ ปี 2554",
    category: "pat2",
    year: 2554,
    subject: "ฟิสิกส์",
    examType: "PAT2",
    pdfUrl: "/exams/pat2-physics-2554.pdf",
    downloadUrl: "/downloads/pat2-physics-2554.pdf",
  },
  {
    id: 4,
    title: "ข้อสอบ PAT2 วิชา ฟิสิกส์ ปี 2555",
    category: "pat2",
    year: 2555,
    subject: "ฟิสิกส์",
    examType: "PAT2",
    pdfUrl: "/exams/pat2-physics-2555.pdf",
    downloadUrl: "/downloads/pat2-physics-2555.pdf",
  },
  {
    id: 5,
    title: "ข้อสอบ PAT2 วิชา ฟิสิกส์ ปี 2556",
    category: "pat2",
    year: 2556,
    subject: "ฟิสิกส์",
    examType: "PAT2",
    pdfUrl: "/exams/pat2-physics-2556.pdf",
    downloadUrl: "/downloads/pat2-physics-2556.pdf",
  },
  {
    id: 6,
    title: "ข้อสอบ PAT2 วิชา ฟิสิกส์ ปี 2557",
    category: "pat2",
    year: 2557,
    subject: "ฟิสิกส์",
    examType: "PAT2",
    pdfUrl: "/exams/pat2-physics-2557.pdf",
    downloadUrl: "/downloads/pat2-physics-2557.pdf",
  },
  {
    id: 7,
    title: "ข้อสอบ PAT2 วิชา ฟิสิกส์ ปี 2558",
    category: "pat2",
    year: 2558,
    subject: "ฟิสิกส์",
    examType: "PAT2",
    pdfUrl: "/exams/pat2-physics-2558.pdf",
    downloadUrl: "/downloads/pat2-physics-2558.pdf",
  },
  {
    id: 8,
    title: "ข้อสอบ PAT2 วิชา ฟิสิกส์ ปี 2559",
    category: "pat2",
    year: 2559,
    subject: "ฟิสิกส์",
    examType: "PAT2",
    pdfUrl: "/exams/pat2-physics-2559.pdf",
    downloadUrl: "/downloads/pat2-physics-2559.pdf",
  },
  {
    id: 9,
    title: "ข้อสอบ PAT2 วิชา ฟิสิกส์ ปี 2560",
    category: "pat2",
    year: 2560,
    subject: "ฟิสิกส์",
    examType: "PAT2",
    pdfUrl: "/exams/pat2-physics-2560.pdf",
    downloadUrl: "/downloads/pat2-physics-2560.pdf",
  },
 
  {
    id: 10,
    title: "ข้อสอบ A LEVEL ปี 2555",
    category: "alevel",
    year: 2555,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2555.pdf",
    downloadUrl: "/downloads/alevel-physics-2555.pdf",
  },
  {
    id: 11,
    title: "ข้อสอบ A LEVEL ปี 2556",
    category: "alevel",
    year: 2556,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2556.pdf",
    downloadUrl: "/downloads/alevel-physics-2556.pdf",
  },
  {
    id: 12,
    title: "ข้อสอบ A LEVEL ปี 2557",
    category: "alevel",
    year: 2557,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2557.pdf",
    downloadUrl: "/downloads/alevel-physics-2557.pdf",
  },
  {
    id: 13,
    title: "ข้อสอบ A LEVEL ปี 2558",
    category: "alevel",
    year: 2558,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2558.pdf",
    downloadUrl: "/downloads/alevel-physics-2558.pdf",
  },
  {
    id: 14,
    title: "ข้อสอบ A LEVEL ปี 2559",
    category: "alevel",
    year: 2559,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2559.pdf",
    downloadUrl: "/downloads/alevel-physics-2559.pdf",
  },
  {
    id: 15,
    title: "ข้อสอบ A LEVEL ปี 2560",
    category: "alevel",
    year: 2560,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2560.pdf",
    downloadUrl: "/downloads/alevel-physics-2560.pdf",
  },
  {
    id: 16,
    title: "ข้อสอบ A LEVEL ปี 2561",
    category: "alevel",
    year: 2561,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2561.pdf",
    downloadUrl: "/downloads/alevel-physics-2561.pdf",
  },
  {
    id: 17,
    title: "ข้อสอบ A LEVEL ปี 2562",
    category: "alevel",
    year: 2562,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2562.pdf",
    downloadUrl: "/downloads/alevel-physics-2562.pdf",
  },
  {
    id: 18,
    title: "ข้อสอบ A LEVEL ปี 2563",
    category: "alevel",
    year: 2563,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2563.pdf",
    downloadUrl: "/downloads/alevel-physics-2563.pdf",
  },
  {
    id: 19,
    title: "ข้อสอบ A LEVEL ปี 2564",
    category: "alevel",
    year: 2564,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2564.pdf",
    downloadUrl: "/downloads/alevel-physics-2564.pdf",
  },
  {
    id: 20,
    title: "ข้อสอบ A LEVEL ปี 2565",
    category: "alevel",
    year: 2565,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2565.pdf",
    downloadUrl: "/downloads/alevel-physics-2565.pdf",
  },
  {
    id: 21,
    title: "ข้อสอบ A LEVEL ปี 2566",
    category: "alevel",
    year: 2566,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2566.pdf",
    downloadUrl: "/downloads/alevel-physics-2566.pdf",
  },
  {
    id: 22,
    title: "ข้อสอบ A LEVEL ปี 2567",
    category: "alevel",
    year: 2567,
    subject: "ฟิสิกส์",
    examType: "A LEVEL",
    pdfUrl: "/exams/alevel-physics-2567.pdf",
    downloadUrl: "/downloads/alevel-physics-2567.pdf",
  },
 
  {
    id: 23,
    title: "ข้อสอบสอวน.ฟิสิกส์ คัดค่าย 1 ปี 2560",
    category: "physics-olympiad",
    year: 2560,
    subject: "ฟิสิกส์",
    examType: "สอวน.ฟิสิกส์ คัดค่าย 1",
    pdfUrl: "/exams/physics-olympiad-2560.pdf",
    downloadUrl: "/downloads/physics-olympiad-2560.pdf",
  },
  {
    id: 24,
    title: "ข้อสอบสอวน.ฟิสิกส์ คัดค่าย 1 ปี 2561",
    category: "physics-olympiad",
    year: 2561,
    subject: "ฟิสิกส์",
    examType: "สอวน.ฟิสิกส์ คัดค่าย 1",
    pdfUrl: "/exams/physics-olympiad-2561.pdf",
    downloadUrl: "/downloads/physics-olympiad-2561.pdf",
  },
  {
    id: 25,
    title: "ข้อสอบสอวน.ฟิสิกส์ คัดค่าย 1 ปี 2562",
    category: "physics-olympiad",
    year: 2562,
    subject: "ฟิสิกส์",
    examType: "สอวน.ฟิสิกส์ คัดค่าย 1",
    pdfUrl: "/exams/physics-olympiad-2562.pdf",
    downloadUrl: "/downloads/physics-olympiad-2562.pdf",
  },

  {
    id: 26,
    title: "ข้อสอบความถนัดวิศวกรรม (TPAT3) ปี 2557",
    category: "tpat3",
    year: 2557,
    subject: "ความถนัดวิศวกรรม",
    examType: "TPAT3",
    pdfUrl: "/exams/tpat3-2557.pdf",
    downloadUrl: "/downloads/tpat3-2557.pdf",
  },
  {
    id: 27,
    title: "ข้อสอบความถนัดวิศวกรรม (TPAT3) ปี 2558",
    category: "tpat3",
    year: 2558,
    subject: "ความถนัดวิศวกรรม",
    examType: "TPAT3",
    pdfUrl: "/exams/tpat3-2558.pdf",
    downloadUrl: "/downloads/tpat3-2558.pdf",
  },
  {
    id: 28,
    title: "ข้อสอบความถนัดวิศวกรรม (TPAT3) ปี 2559",
    category: "tpat3",
    year: 2559,
    subject: "ความถนัดวิศวกรรม",
    examType: "TPAT3",
    pdfUrl: "/exams/tpat3-2559.pdf",
    downloadUrl: "/downloads/tpat3-2559.pdf",
  },
  {
    id: 29,
    title: "ข้อสอบความถนัดวิศวกรรม (TPAT3) ปี 2560",
    category: "tpat3",
    year: 2560,
    subject: "ความถนัดวิศวกรรม",
    examType: "TPAT3",
    pdfUrl: "/exams/tpat3-2560.pdf",
    downloadUrl: "/downloads/tpat3-2560.pdf",
  },
  {
    id: 30,
    title: "ข้อสอบความถนัดวิศวกรรม (TPAT3) ปี 2561",
    category: "tpat3",
    year: 2561,
    subject: "ความถนัดวิศวกรรม",
    examType: "TPAT3",
    pdfUrl: "/exams/tpat3-2561.pdf",
    downloadUrl: "/downloads/tpat3-2561.pdf",
  },
]
